micronaut:
  application:
    name: azulerosa
  security:
    intercept-url-map:
      - pattern: /swagger*/**
        access:
          - isAnonymous()
      - pattern: /v1/login
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAuthenticated()
    enabled: true
    authentication: bearer

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
flyway:
  datasources:
    default:
      enabled: true

security:
  jwt_secret: ${JWT_SECRET}